=== sped-mobi/sql-script-generator/src/TSqlScriptGenerator/Configuration/Database.xsd
<?xml version="1.0" encoding="utf-8"?>
<!--
Sample license text.
-->

<xs:schema
  attributeFormDefault="unqualified"
  elementFormDefault="qualified"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="GenerationOptions" type="GenerationOptions">
    <xs:annotation>
      <xs:documentation>Represents options for generating sql scripts.</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:complexType name="GenerationOptions">
    <xs:sequence>
      <xs:element name="AlignClauseBodies" type="xs:boolean" default="false" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Gets or sets a boolean indicating if there should be a newline before the OFFSET clause.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="AlignColumnDefinitionFields" type="xs:boolean"  default="false" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Gets or sets a boolean indicating if the INSERT column sources list should be spread across multiple lines.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="AlignSetClauseItem" type="xs:boolean"  default="false" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Gets or sets a boolean indicating if the INSERT column targets list should be spread across multiple lines</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="AsKeywordOnOwnLine" type="xs:boolean" default="false" minOccurs="0">
        <xs:annotation>
          <xs:documentation></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="IncludeSemicolons" type="xs:boolean"  default="false" minOccurs="0">
        <xs:annotation>
          <xs:documentation></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="IndentationSize" type="xs:unsignedByte" default="1" minOccurs="0">
        <xs:annotation>
          <xs:documentation></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="IndentSetClause" type="xs:boolean"  default="false" minOccurs="0">
        <xs:annotation>
          <xs:documentation></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="IndentViewBody" type="xs:boolean"  default="false" minOccurs="0">
        <xs:annotation>
          <xs:documentation></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="KeywordCasing" type="KeywordCasing" default="Uppercase" minOccurs="0">
        <xs:annotation>
          <xs:documentation></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="MultilineInsertSourcesList" type="xs:boolean"  default="false" minOccurs="0">
        <xs:annotation>
          <xs:documentation></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="MultilineInsertTargetsList" type="xs:boolean"  default="false" minOccurs="0">
        <xs:annotation>
          <xs:documentation></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="MultilineSelectElementsList" type="xs:boolean"  default="false" minOccurs="0">
        <xs:annotation>
          <xs:documentation></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="MultilineSetClauseItems" type="xs:boolean"  default="false" minOccurs="0">
        <xs:annotation>
          <xs:documentation></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="MultilineViewColumnsList" type="xs:boolean"  default="false" minOccurs="0">
        <xs:annotation>
          <xs:documentation></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="MultilineWherePredicatesList" type="xs:boolean"  default="false" minOccurs="0">
        <xs:annotation>
          <xs:documentation></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="NewLineBeforeCloseParenthesisInMultilineList" type="xs:boolean"  default="false" minOccurs="0">
        <xs:annotation>
          <xs:documentation></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="NewLineBeforeFromClause" type="xs:boolean"  default="false" minOccurs="0">
        <xs:annotation>
          <xs:documentation></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="NewLineBeforeGroupByClause" type="xs:boolean"  default="false" minOccurs="0">
        <xs:annotation>
          <xs:documentation></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="NewLineBeforeHavingClause" type="xs:boolean"  default="false" minOccurs="0">
        <xs:annotation>
          <xs:documentation></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="NewLineBeforeJoinClause" type="xs:boolean"  default="false" minOccurs="0">
        <xs:annotation>
          <xs:documentation></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="NewLineBeforeOffsetClause" type="xs:boolean"  default="false" minOccurs="0">
        <xs:annotation>
          <xs:documentation></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="NewLineBeforeOpenParenthesisInMultilineList" type="xs:boolean"  default="false" minOccurs="0">
        <xs:annotation>
          <xs:documentation></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="NewLineBeforeOrderByClause" type="xs:boolean"  default="false" minOccurs="0">
        <xs:annotation>
          <xs:documentation></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="NewLineBeforeOutputClause" type="xs:boolean"  default="false" minOccurs="0">
        <xs:annotation>
          <xs:documentation></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="NewLineBeforeWhereClause" type="xs:boolean"  default="false" minOccurs="0">
        <xs:annotation>
          <xs:documentation></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="SqlVersion" type="SqlVersion"  default="Sql150" minOccurs="0">
        <xs:annotation>
          <xs:documentation></xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="Schemas" type="Schemas">
    <xs:annotation>
      <xs:documentation>
        Represents a collection of database schemas.
      </xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:complexType name="Schemas">
    <xs:sequence>
      <xs:element ref="Schema" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:element name="Schema" type="Schema">
    <xs:annotation>
      <xs:documentation>
        Represents a database schema.
      </xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:complexType name="Schema">
    <xs:attribute name="Name" type="xs:string">
      <xs:annotation>
        <xs:documentation>
          The name of the schema.
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="DbDefault" type="xs:boolean">
      <xs:annotation>
        <xs:documentation>
          Determines whether or not this schema is a default schema.
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:element name="Tables" type="Tables" />
  <xs:complexType name="Tables">
    <xs:sequence>
      <xs:element ref="Table" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:element name="Table" type="Table" />
  <xs:complexType name="Table">
    <xs:sequence>
      <xs:element ref="Columns" minOccurs="0" />
      <xs:element ref="Indexes" minOccurs="0" />
      <xs:element ref="ForeignKeys" minOccurs="0" />
    </xs:sequence>
    <xs:attribute name="Schema" type="xs:string" />
    <xs:attribute name="Name" type="xs:string" />
  </xs:complexType>

  <xs:element name="Indexes" type="Indexes" />
  <xs:complexType name="Indexes">
    <xs:sequence>
      <xs:element ref="Index" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:element name="Index" type="Index" />
  <xs:complexType name="Index">
    <xs:sequence>
      <xs:element ref="Members" minOccurs="0" />
    </xs:sequence>
    <xs:attribute name="Name" type="xs:string" />
    <xs:attribute name="IsClustered" type="xs:boolean" />
    <xs:attribute name="IsUnique" type="xs:boolean" />
    <xs:attribute name="IsPrimary" type="xs:boolean" />
  </xs:complexType>

  <xs:element name="Members" type="Members" />
  <xs:complexType name="Members">
    <xs:sequence>
      <xs:element ref="Member" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:element name="Member" type="Member" />
  <xs:complexType name="Member">
    <xs:attribute name="Column" type="xs:string" />
    <xs:attribute name="Position" type="xs:int" />
    <xs:attribute name="IsIncluded" type="xs:boolean" />
  </xs:complexType>

  <xs:element name="Columns" type="Columns" />
  <xs:complexType name="Columns">
    <xs:sequence>
      <xs:element ref="Column" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:element name="Column" type="Column" />
  <xs:complexType name="Column">
    <xs:attribute name="Name" type="xs:string" />
    <xs:attribute name="Position" type="xs:int" />
    <xs:attribute name="DataType" type="xs:string" />
    <xs:attribute name="IsIdentity" type="xs:boolean" use="optional" />
    <xs:attribute name="IdentitySeed" type="xs:int" use="optional" />
    <xs:attribute name="IdentityIncrement" type="xs:int" use="optional" />
    <xs:attribute name="AllowNulls" type="xs:boolean" use="optional" />
    <xs:attribute name="RowGuid" type="xs:boolean" use="optional" />
    <xs:attribute name="DefaultName" type="xs:string" use="optional" />
    <xs:attribute name="DefaultValue" type="xs:string" use="optional" />
  </xs:complexType>

  <xs:element name="ForeignKeys" type="ForeignKeys" />
  <xs:complexType name="ForeignKeys">
    <xs:sequence>
      <xs:element ref="ForeignKey" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:element name="ForeignKey" type="ForeignKey" />
  <xs:complexType name="ForeignKey">
    <xs:sequence>
      <xs:element ref="ForeignKeyColumns" minOccurs="0" />
    </xs:sequence>
    <xs:attribute name="Name" type="xs:string" />
    <xs:attribute name="PkTableSchema" type="xs:string" />
    <xs:attribute name="PkTable" type="xs:string" />
  </xs:complexType>

  <xs:element name="ForeignKeyColumns" type="ForeignKeyColumns" />
  <xs:complexType name="ForeignKeyColumns">
    <xs:sequence>
      <xs:element ref="ForeignKeyColumn" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:element name="ForeignKeyColumn" type="ForeignKeyColumn" />
  <xs:complexType name="ForeignKeyColumn">
    <xs:attribute name="FkColumn" type="xs:string" />
    <xs:attribute name="Position" type="xs:int" />
    <xs:attribute name="PkColumn" type="xs:string" />
  </xs:complexType>


  <xs:element name="Database" type="Database" />
  <xs:complexType name="Database">
    <xs:sequence>
      <xs:element ref="GenerationOptions" minOccurs="0" />
      <xs:element ref="Schemas" />
      <xs:element ref="Tables" />
    </xs:sequence>
    <xs:attribute name="Version" type="xs:string" />
    <xs:attribute name="DatabaseName" type="xs:string" />
  </xs:complexType>

  <xs:simpleType name="SqlVersion">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Sql09" />
      <xs:enumeration value="Sql08" />
      <xs:enumeration value="Sql10" />
      <xs:enumeration value="Sql110" />
      <xs:enumeration value="Sql120" />
      <xs:enumeration value="Sql130" />
      <xs:enumeration value="Sql140" />
      <xs:enumeration value="Sql150" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="KeywordCasing">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Uppercase" />
      <xs:enumeration value="Lowercase" />
      <xs:enumeration value="PascalCase" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="SqlType">
    <xs:restriction base="xs:string">
      <!--<xs:pattern value="[a-z]+(\(([0-9]*(, ?[0-9]*)?|MAX)\))?" />-->
      <xs:enumeration value="tinyint" />
      <xs:enumeration value="smallint" />
      <xs:enumeration value="bigint" />
      <xs:enumeration value="int" />
      <xs:enumeration value="smallmoney" />
      <xs:enumeration value="money" />
      <xs:enumeration value="float" />
      <xs:enumeration value="real" />
      <xs:enumeration value="numeric" />
      <xs:enumeration value="bit" />
      <xs:enumeration value="decimal" />
      <xs:enumeration value="date" />
      <xs:enumeration value="datetimeoffset" />
      <xs:enumeration value="datetime2" />
      <xs:enumeration value="smalldatetime" />
      <xs:enumeration value="datetime" />
      <xs:enumeration value="time" />
      <xs:enumeration value="char" />
      <xs:enumeration value="varchar" />
      <xs:enumeration value="text" />
      <xs:enumeration value="nchar" />
      <xs:enumeration value="nvarchar" />
      <xs:enumeration value="ntext" />
      <xs:enumeration value="binary" />
      <xs:enumeration value="varbinary" />
      <xs:enumeration value="image" />
      <xs:enumeration value="cursor" />
      <xs:enumeration value="rowversion" />
      <xs:enumeration value="hierarchyid" />
      <xs:enumeration value="uniqueidentifier" />
      <xs:enumeration value="sql_variant" />
      <xs:enumeration value="xml" />
      <xs:enumeration value="table" />
      <xs:enumeration value="geography" />
      <xs:enumeration value="geometry" />
    </xs:restriction>
  </xs:simpleType>


</xs:schema>

=== sped-mobi/sql-script-generator/src/TSqlScriptGenerator/Database.xml
<Database Version="2" DatabaseName="SpedHubDB" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Configuration/Database.xsd">
  <GenerationOptions>
    <AlignClauseBodies>true</AlignClauseBodies>
    <AlignColumnDefinitionFields>true</AlignColumnDefinitionFields>
    <AlignSetClauseItem>true</AlignSetClauseItem>
    <AsKeywordOnOwnLine>true</AsKeywordOnOwnLine>
    <IncludeSemicolons>true</IncludeSemicolons>
    <IndentationSize>4</IndentationSize>
    <IndentSetClause>true</IndentSetClause>
    <IndentViewBody>true</IndentViewBody>
    <KeywordCasing>Uppercase</KeywordCasing>
    <MultilineInsertSourcesList>true</MultilineInsertSourcesList>
    <MultilineInsertTargetsList>true</MultilineInsertTargetsList>
    <MultilineSelectElementsList>true</MultilineSelectElementsList>
    <MultilineSetClauseItems>true</MultilineSetClauseItems>
    <MultilineViewColumnsList>true</MultilineViewColumnsList>
    <MultilineWherePredicatesList>true</MultilineWherePredicatesList>
    <NewLineBeforeCloseParenthesisInMultilineList>true</NewLineBeforeCloseParenthesisInMultilineList>
    <NewLineBeforeFromClause>true</NewLineBeforeFromClause>
    <NewLineBeforeGroupByClause>true</NewLineBeforeGroupByClause>
    <NewLineBeforeHavingClause>true</NewLineBeforeHavingClause>
    <NewLineBeforeJoinClause>true</NewLineBeforeJoinClause>
    <NewLineBeforeOffsetClause>true</NewLineBeforeOffsetClause>
    <NewLineBeforeOpenParenthesisInMultilineList>true</NewLineBeforeOpenParenthesisInMultilineList>
    <NewLineBeforeOrderByClause>true</NewLineBeforeOrderByClause>
    <NewLineBeforeOutputClause>true</NewLineBeforeOutputClause>
    <NewLineBeforeWhereClause>true</NewLineBeforeWhereClause>
    <SqlVersion>Sql150</SqlVersion>
  </GenerationOptions>
  <Schemas>
    <Schema Name="dbo" DbDefault="1" />
    <Schema Name="guest" DbDefault="1" />
    <Schema Name="db_owner" DbDefault="1" />
    <Schema Name="db_accessadmin" DbDefault="1" />
    <Schema Name="db_securityadmin" DbDefault="1" />
    <Schema Name="db_ddladmin" DbDefault="1" />
    <Schema Name="db_backupoperator" DbDefault="1" />
    <Schema Name="db_datareader" DbDefault="1" />
    <Schema Name="db_datawriter" DbDefault="1" />
    <Schema Name="db_denydatareader" DbDefault="1" />
    <Schema Name="db_denydatawriter" DbDefault="1" />
  </Schemas>
  <Tables>
    <Table Schema="dbo" Name="CaseManager">
      <Columns>
        <Column Name="ID" IsIdentity="1" IdentitySeed="1" IdentityIncrement="1" DataType="INT" />
        <Column Name="FirstName" DataType="VARCHAR(MAX)" AllowNulls="0" />
        <Column Name="MiddleName" DataType="VARCHAR(MAX)" AllowNulls="1" />
        <Column Name="LastName" DataType="VARCHAR(MAX)" AllowNulls="0" />
      </Columns>
      <Indexes>
        <Index Name="PK_CaseManager_ID" IsPrimary="1" IsClustered="1" IsUnique="1">
          <Members>
            <Member Column="ID" />
          </Members>
        </Index>
      </Indexes>
    </Table>
    <Table Schema="dbo" Name="EducationPlan">
      <Columns>
        <Column Name="ID" IsIdentity="1" IdentitySeed="1" IdentityIncrement="1" DataType="INT" />
        <Column Name="ValidStart" DataType="DATETIME" AllowNulls="0"/>
        <Column Name="ValidEnd" DataType="DATETIME" AllowNulls="0"/>
      </Columns>
      <Indexes>
        <Index Name="PK_EducationPlan_ID" IsPrimary="1" IsClustered="1" IsUnique="1">
          <Members>
            <Member Column="ID" />
          </Members>
        </Index>
      </Indexes>
    </Table>
    <Table Schema="dbo" Name="Accommodation">
      <Columns>
        <Column Name="ID" IsIdentity="1" IdentitySeed="1" IdentityIncrement="1" DataType="INT" />
        <Column Name="Description" DataType="VARCHAR(MAX)"/>
        <Column Name="Category" DataType="VARCHAR(MAX)"/>
      </Columns>
      <Indexes>
        <Index Name="PK_Accommodation_ID" IsPrimary="1" IsClustered="1" IsUnique="1">
          <Members>
            <Member Column="ID" />
          </Members>
        </Index>
      </Indexes>
    </Table>
    <Table Schema="dbo" Name="Subject">
      <Columns>
        <Column Name="ID" IsIdentity="1" IdentitySeed="1" IdentityIncrement="1" DataType="INT" />
        <Column Name="Description" DataType="VARCHAR(MAX)" AllowNulls="0"/>
      </Columns>
      <Indexes>
        <Index Name="PK_Subject_ID" IsPrimary="1" IsClustered="1" IsUnique="1">
          <Members>
            <Member Column="ID" />
          </Members>
        </Index>
      </Indexes>
    </Table>
    <Table Schema="dbo" Name="AccommodationReference">
      <Columns>
        <Column Name="ID" IsIdentity="1" IdentitySeed="1" IdentityIncrement="1" DataType="INT" />
        <Column Name="EducationPlanID" DataType="INT" AllowNulls="1" />
        <Column Name="AccommodationID" DataType="INT" AllowNulls="1" />
      </Columns>
      <Indexes>
        <Index Name="PK_AccommodationReference_ID" IsPrimary="1" IsClustered="1" IsUnique="1">
          <Members>
            <Member Column="ID" />
          </Members>
        </Index>
      </Indexes>
      <ForeignKeys>
        <ForeignKey Name="FK_AccommodationReference_EducationPlanID" PkTableSchema="dbo" PkTable="EducationPlan">
          <ForeignKeyColumns>
            <ForeignKeyColumn FkColumn="EducationPlanID" PkColumn="ID" />
          </ForeignKeyColumns>
        </ForeignKey>
        <ForeignKey Name="FK_AccommodationReference_AccommodationID" PkTableSchema="dbo" PkTable="Accommodation">
          <ForeignKeyColumns>
            <ForeignKeyColumn FkColumn="AccommodationID" PkColumn="ID" />
          </ForeignKeyColumns>
        </ForeignKey>
      </ForeignKeys>
    </Table>
    <Table Schema="dbo" Name="SubjectReference">
      <Columns>
        <Column Name="ID" IsIdentity="1" IdentitySeed="1" IdentityIncrement="1" DataType="INT" />
        <Column Name="AccommodationReferenceID" DataType="INT" AllowNulls="1" />
        <Column Name="SubjectID" DataType="INT" AllowNulls="1" />
      </Columns>
      <Indexes>
        <Index Name="PK_SubjectReference_ID" IsPrimary="1" IsClustered="1" IsUnique="1">
          <Members>
            <Member Column="ID" />
          </Members>
        </Index>
      </Indexes>
      <ForeignKeys>
        <ForeignKey Name="FK_SubjectReference_AccommodationReferenceID" PkTableSchema="dbo" PkTable="AccommodationReference">
          <ForeignKeyColumns>
            <ForeignKeyColumn FkColumn="AccommodationReferenceID" PkColumn="ID" />
          </ForeignKeyColumns>
        </ForeignKey>
        <ForeignKey Name="FK_SubjectReference_SubjectID" PkTableSchema="dbo" PkTable="Subject">
          <ForeignKeyColumns>
            <ForeignKeyColumn FkColumn="SubjectID" PkColumn="ID" />
          </ForeignKeyColumns>
        </ForeignKey>
      </ForeignKeys>
    </Table>
    <Table Schema="dbo" Name="PresentLevel">
      <Columns>
        <Column Name="ID" IsIdentity="1" IdentitySeed="1" IdentityIncrement="1" DataType="INT" />
        <Column Name="EducationPlanID" DataType="INT" AllowNulls="1" />
        <Column Name="Subject" DataType="VARCHAR(MAX)"/>
        <Column Name="Statement" DataType="TEXT"/>
      </Columns>
      <Indexes>
        <Index Name="PK_PresentLevel_ID" IsPrimary="1" IsClustered="1" IsUnique="1">
          <Members>
            <Member Column="ID" />
          </Members>
        </Index>
      </Indexes>
      <ForeignKeys>
        <ForeignKey Name="FK_PresentLevel_EducationPlanID" PkTableSchema="dbo" PkTable="EducationPlan">
          <ForeignKeyColumns>
            <ForeignKeyColumn FkColumn="EducationPlanID" PkColumn="ID" />
          </ForeignKeyColumns>
        </ForeignKey>
      </ForeignKeys>
    </Table>
    <Table Schema="dbo" Name="Student">
      <Columns>
        <Column Name="ID" IsIdentity="1" IdentitySeed="1" IdentityIncrement="1" DataType="INT" />
        <Column Name="CaseManagerID" DataType="INT" AllowNulls="1" />
        <Column Name="FirstName" DataType="VARCHAR(MAX)" AllowNulls="0" />
        <Column Name="MiddleName" DataType="VARCHAR(MAX)" AllowNulls="1" />
        <Column Name="LastName" DataType="VARCHAR(MAX)" AllowNulls="0" />
        <Column Name="DateOfBirth" DataType="DATETIME" AllowNulls="1"/>
        <Column Name="Gender" DataType="BIT" AllowNulls="0" />
        <Column Name="GradeLevel" DataType="INT" AllowNulls="0"/>
      </Columns>
      <Indexes>
        <Index Name="PK_Student_ID" IsPrimary="1" IsClustered="1" IsUnique="1">
          <Members>
            <Member Column="ID" />
          </Members>
        </Index>
      </Indexes>
      <ForeignKeys>
        <ForeignKey Name="FK_Student_CaseManagerID" PkTableSchema="dbo" PkTable="CaseManager">
          <ForeignKeyColumns>
            <ForeignKeyColumn FkColumn="CaseManagerID" PkColumn="ID" />
          </ForeignKeyColumns>
        </ForeignKey>
      </ForeignKeys>
    </Table>

  </Tables>
</Database>
